name: test cosign

on:
    workflow_dispatch: 


permissions:
      contents: read
      packages: write
      id-token: write 


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out directory
              uses: actions/checkout@v4
            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.7.0
            - name: Check install!
              run: cosign version
            - name: Sign a file
              run: |
                cosign sign-blob --yes README.md --bundle README.md.cosign.bundle
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: cosign.bundle
                path: README.md.cosign.bundle
            