name: Attestation Action

on:
    workflow_dispatch: 


permissions:
      contents: read
      packages: write
      id-token: write 
      attestations: write


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out directory
              uses: actions/checkout@v4
            - uses: actions/attest-build-provenance@v1
              id: attest
              with:
                subject-path: README.md

            - run: cp ${{ steps.attest.outputs.bundle-path }} .
              name: Copy bundle to current directory to not mess up zips later

            - uses: actions/upload-artifact@v4
              with:
                name: Build Artifacts
                path: | 
                  README.md
                  ${{ steps.attest.outputs.bundle-path }}

            - name: The Cosign Command
              run: echo cosign verify-blob README.md --bundle attestation.jsonl --new-bundle-format --cert-oidc-issuer https://token.actions.githubusercontent.com --cert-identity https://github.com/${GITHUB_WORKFLOW_REF}
            - name: The Rekor URI
              run: | 
                logIndex=$(jq -r '.verificationMaterial.tlogEntries[0].logIndex' < ${{ steps.attest.outputs.bundle-path }})
                echo https://search.sigstore.dev/?logIndex=${logIndex}